# Generated by Django 5.2.7 on 2025-10-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Portel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User')], default='user', max_length=10),
        ),
    ]
