# Generated by Django 5.2.7 on 2025-10-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Portel', '0002_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(blank=True, max_length=100, null=True)),
                ('option1', models.CharField(blank=True, max_length=100, null=True)),
                ('option2', models.CharField(blank=True, max_length=100, null=True)),
                ('option3', models.CharField(blank=True, max_length=100, null=True)),
                ('option4', models.CharField(blank=True, max_length=100, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
