# Generated by Django 5.2.7 on 2025-10-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_Portel', '0003_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='correct_answer',
            field=models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3'), ('option4', 'Option 4')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
